### ISSUE TITLE
From images testrail/apache:6.0 - not work ldap

### ISSUE THREAD

**Issue by cnolick** [cbreit/testrail-docker#2]
just doesn't work :( 

I rebuild 6.0 from zip archive and ldap began work. This issue has the meaning if you from Gurock if this not official, just skip

**Comment by cbreit** [comment]
Hey.
I've not added ldap to the images yet, so it does not work out of the box.
I should get introduced in the offiicial images in future. For the time being, simply rebuild the image as you did and add the respective file to to the testrail folders as described in the testrail documentation.

**Comment by cnolick** [comment]
Okay :(
